#!/bin/bash
args=("$@")
if [ -e "./${args[1]}_pid.txt" ]; then
	echo "Process ${args[1]} already running"
	exit 1
else
	nohup ${args[0]} > ${args[1]}_log.log 2>&1&
        echo $! > "./${args[1]}_pid.txt"
fi
